#!/bin/bash

source ./.env
echo $TIMETREE_TOKEN 
echo $TIMETREE_BASEURL 
echo $CALENDAR_ID 
echo $CONNPASS_NICKNAME 
python src/main.py $TIMETREE_TOKEN $TIMETREE_BASEURL $TIMETREE_CALENDAR_ID $CONNPASS_NICKNAME 