name: Python package

on:
  workflow_dispatch:
  
  schedule:
    - cron:  "0 0 * * *"  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: pip install
        run: pip install -r requirements.txt
      - name: make env
        run: touch ./.env
      - name: set env1
        run: echo TIMETREE_TOKEN=${{ secrets.TIMETREE_TOKEN }} >> .env\
              echo HOGE=hello >> .env\
              echo TIMETREE_BASEURL=${{ secrets.TIMETREE_BASEURL }} >> .env\
              echo CALENDAR_ID=${{ secrets.CALENDAR_ID }} >> .env\
              echo NICKNAME=${{ secrets.NICKNAME }} >> .env
      - name: cat env1
        run: cat ./.env
      - name: set env2
        run: |
              env TIMETREE_TOKEN=${{ secrets.TIMETREE_TOKEN }}
              env HOGE=hello
              env TIMETREE_BASEURL=${{ secrets.TIMETREE_BASEURL }}
              env CALENDAR_ID=${{ secrets.CALENDAR_ID }}
              env NICKNAME=${{ secrets.NICKNAME }}
      - name: run main.py
        run: python src/main.py