name: connpass to timetree

on:
  workflow_dispatch:
  schedule:
    # 分 時 日 月 曜日
    - cron:  "0 */4 * * *" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: pip install
        run: pip install -r requirements.txt
      - name: run main.py
        run: python src/main.py ${{ secrets.TIMETREE_TOKEN }} ${{ secrets.TIMETREE_CALENDAR_ID }} ${{ secrets.CONNPASS_NICKNAME }}    
      - name: git commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add events.json
          git commit --allow-empty -m 'commit'
          git push origin main
